### ISSUE TITLE
[2.0] Dimension of Key Components

### ISSUE THREAD

**Issue by cls-c** [goscommons/Grapples#16]
Designing the dimension of key components of Grapple 

- [ ] Identifying Customers needs/ Requirement 
- [ ]  Research for standard dimensions based on the existing market products 
- [ ]  Design and document key dimension for each identified component

**Comment by goscommons** [comment]
Hi cls-c we already have all these, you have them on your machine as CAD models.
If you see the hydraulic cylincer issue, or the clamp issue, those are examples of components to be documented, using the cad models. See the example of a card finished done by @krishnarajagopal2011 [Task breakdown and deliverable example](https://github.com/goscommons/Grapples/issues/12)

**Comment by jurra** [comment]
Hi @cls-c this issue, is not making sense at the moment. I am going to close, you can still see it though, to reflect on what you were trying to achieve. But keep in mind that the goal of this sprint is to document already existing parts, so that others can see the technical documentation without having to open a CAD. I allows also fabricators to consider, proper parts dimensions etc.
