### ISSUE TITLE
Idea: protocol for assembly steps documentation

### ISSUE THREAD

**Issue by jurra** [goscommons/Grapples#24]
It can be useful to consider the order of assembly steps in the structure of the cad file, this way we can already know the order of assembly. I put an example of how it can be. In this case the order might be wrong, I just make the point of putting numbers infront of the item names, that show already the order of assembly, This can work in the master cad as well as in subassemblies. 
![image](https://user-images.githubusercontent.com/18581201/39967197-784063f0-56b7-11e8-9d75-39da24412cd1.png)

Maybe the structure of folders could be improved, since now all the parts are together with assembly names. Maybe just putting an A,(Assembly); P (Part) ;(C) Off the shelve component infront of names of files can also help. AA for subassembly first level?

For instance AA_Tynder_Assembly; A_Grapples; C_Hydraulic_Cylinder; etc.

**Comment by polemidis** [comment]
Something that seperates the simple parts from the assemblies would be nice. But some parts belong to multiple assemblies. I think that the current names, with the name tree is sufficient. It’s different to make a few name changes if something is not clear and different to rename every part, change every link on that part on the assembly, and change the description of that part. LOTS of work for no clear benefit, which more than likely it will break up everything, because users are not familiar with the Freecad

**Comment by polemidis** [comment]
But what definitely has to be done in order to go forward with this project is to make .svg or .dxf files of every part that has to be cut in plasma ( all flat parts ). My plasma is ready to cut, I have the air drier set up. Once cut we can have real pictures, see real issues that may slip the CAD detection

**Comment by polemidis** [comment]
And lastly, because that’s a done cad model, if you want to organize , test the cad creation procedure, which is the actual fun :) what about work on the plasma model, that has cad needs? I mean that’s the backbone of every project, and people did not experience this in the grapple because it was already made

**Comment by jurra** [comment]
Agree. Understand what you mean.
